name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    env:
      IMAGE: ghcr.io/gustav951/virtual-diabetes-clinic-grupp-g
      VERSION: ${{ github.ref_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model (writes model.joblib + metrics.json)
        run: python src/train.py

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image (bakes MODEL_VERSION from tag)
        run: docker build --build-arg VERSION=${{ env.VERSION }} -t $IMAGE:${{ env.VERSION }} .

      - name: Smoke test container
        run: bash scripts/smoke.sh $IMAGE:${{ env.VERSION }}

      - name: Push Docker image
        run: docker push $IMAGE:${{ env.VERSION }}

      - name: Upload metrics as artifact
        uses: actions/upload-artifact@v4
        with:
          name: metrics-${{ env.VERSION }}
          path: metrics.json

      - name: Extract release notes from CHANGELOG.md
        run: bash scripts/extract_release_notes.sh ${{ env.VERSION }}

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          body_path: RELEASE_NOTES.md
          files: |
            metrics.json
          draft: false
          prerelease: false
          make_latest: true
