name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    env:
      IMAGE: ghcr.io/${{ github.repository }}
      VERSION: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Train model
        run: python src/train.py

      - name: Build image
        run: docker build --build-arg VERSION=${{ env.VERSION }} -t $IMAGE:${{ env.VERSION }} .

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Smoke test container
        run: bash scripts/smoke.sh $IMAGE:${{ env.VERSION }}

      - name: Push image
        run: docker push $IMAGE:${{ env.VERSION }}

      - name: Extract release notes
        run: bash scripts/extract_release_notes.sh ${{ env.VERSION }}

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          body_path: RELEASE_NOTES.md
          files: |
            metrics.json
